<?php

if(isset($_POST['submit'])){

    $name = $_POST['name'];
    $subject = $_POST['subject'];
    $mailFrom = $_POST['mail'];
    $message = $_POST['message'];

    $mailTo = "contact.abdelaziz.dev.java@gmail.com";
    $headers = "From: ".$mailFrom;
    $txt = "Vous avez reçu un message de ".$name.".\n\n".$message;

    mail($mailTo, $subject, $txt, $headers);
    header("Location: contact.php?mailsend");
}

require_once('vendor/autoload.php');

$transport = (new Swift_SmtpTransport('smtp.mailtrap.io', 587))
    ->setUsername('0e7d364ef1b1be') // generated by Mailtrap
    ->setPassword('f804e21fe85b60'); // generated by Mailtrap

$mailer = new Swift_Mailer($transport);

// Create the message
if (isset($subject, $mailFrom, $message, $name)) {
    $message = (new Swift_Message())
        // Add subject
        ->setSubject($subject)

        //Put the From address
        ->setFrom([$mailFrom => $name])
        ->setBody('Vous avez reçu un message de ' . $name . ' contenu du message: ' . $message)

        // Include several To addresses
        ->setTo(['newuser@example.com' => 'New Mailtrap user']);
}


if (isset($message)) {
    $result =   $mailer->send($message);
}




